Document: openlayers
Title: Debian openlayers Manual
Author: <insert document author here>
Abstract: This manual describes what openlayers is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openlayers/openlayers.sgml.gz

Format: postscript
Files: /usr/share/doc/openlayers/openlayers.ps.gz

Format: text
Files: /usr/share/doc/openlayers/openlayers.text.gz

Format: HTML
Index: /usr/share/doc/openlayers/html/index.html
Files: /usr/share/doc/openlayers/html/*.html

  
